name: tdc-tcr-epitope-binding-affinity-env
# conda env create -f environment.yml
# conda activate tdc-tcr-epitope-binding-affinity-env

channels:
- pytorch
- nvidia
- conda-forge
- defaults
dependencies:
- accelerate
- jupyter
- pandas
- peft
- pip
- PyTDC
- python
- pytorch
- pytorch-cuda
- torchvision
- torchaudio
- transformers
- xgboost
